### ISSUE TITLE
CSS classes don't seem to work, only element selectors

### ISSUE THREAD

**Issue by chrissainty** [xamarin/MobileBlazorBindings#104]
Hey,

I've been trying to get CSS styling to work using classes for the last hour with no joy. The only styling I can get to work is using element selectors. For example, I have the following label in my component.

```razor
<Label Text="SET YOUR BUDGET" class="redText" />
```

In my CSS file, I have the following class.

```css
.redText {
    color: red;
    margin-bottom: 50;
}
```

When I run the application none of my styles are applied to the label. However, if I change my CSS to style any `Label` element, then it works.

```css
label {
    color: red;
    margin-bottom: 50;
}
```

I've looked at the Weather sample project which uses CSS and I can't see where I'm going wrong.
